version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pg_container
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: intermediadm
    ports:
      - "5555:5432"
    networks:
      - pg_network

  auction-be:
    container_name: auction-be
    build: ./
    ports:
      - 9090:8080
    environment:
      HOST: postgres
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      DB: ${DB}
      DB_PORT: 5432
      DIALECT: ${DIALECT}
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

